"""Regenerate the firmware table from the vendored timezone database."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / 'main/net/tzdb'


def generate():
    zones = json.loads((DB / 'zones.json').read_text(encoding='utf-8'))
    assert zones and all(isinstance(k, str) and isinstance(v, str) and
                         0 < len(k) < 128 and 0 < len(v) < 128
                         for k, v in zones.items())
    return ('/* Generated by tools/generate_timezones.py; do not edit. */\n' +
            ''.join('    {%s, %s},\n' % (json.dumps(k), json.dumps(v))
                    for k, v in sorted(zones.items())))


if __name__ == '__main__':
    (DB / 'zones.inc').write_text(generate(), encoding='utf-8', newline='\n')
